name: streamit_flutter
description: A new Flutter application.
version: 10.0.0+73

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Required
  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2

  # Html
  html: ^0.15.6
  http: ^1.6.0
  flutter_html: ^3.0.0-beta.2

  # Voice Search
  speech_to_text: ^7.3.0

  # State Management
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # Font
  google_fonts: ^6.3.0

  # Launch url
  url_launcher: ^6.3.2

  # Ads
  google_mobile_ads: ^6.0.0

  # Image selection
  image_picker: ^1.2.1

  # Video player
  youtube_player_flutter: ^9.1.3
  pod_player:
    git:
      url: https://github.com/iqonic-design/pod_player.git
      ref: 1.0.0
  cast: ^2.1.0

  # Web-views
  webview_flutter: ^4.13.0
  flutter_custom_tabs: ^2.4.0

  # Animation
  lottie: ^3.3.2

  # Firebase remote config
  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.2
  firebase_crashlytics: ^5.0.5

  #Firebase Notification
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4

  #Social Login
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  the_apple_sign_in: ^1.1.1

  # Prevent Screenshot and Screen record
  screen_protector: ^1.4.6

  # shimmer effect
  shimmer: ^3.0.0

  # Share link
  share_plus: ^12.0.1

  # Download file and store
  flutter_downloader: ^1.12.0
  device_info_plus: ^12.2.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

  #others
  percent_indicator: ^4.2.5
  stream_transform: ^2.1.1
  fl_pip: ^3.2.1
  country_picker: ^2.0.27
  visibility_detector: ^0.4.0+2

  flutter_localizations:
    sdk: flutter
  xml: ^6.5.0

dependency_overrides:
  intl: ^0.20.2
  bonsoir: ^5.0.0

  # in App Purchase
  purchases_flutter: ^9.9.6


  crypto: any
  async: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.4
  build_runner: ^2.10.3
  



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/gif/
    - assets/images/
    - assets/images/flag/
    - assets/